---
title: "create_parameter_table"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{create_parameter_table}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include = FALSE}
library(mxsem)
```

The core function of **mxsem** is to create a parameter table, where are loadings,
regressions, and (co-)variances are specified. This parameter table is then used
to set up an **mxModel** using the `mxPath`-function. It can be useful to
visually inspect the parameter table created by **mxsem**. To this end, set
the `return_parameter_table`-argument to `TRUE`:

```{r}
library(mxsem)

model <- '
  # latent variable definitions
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + a1*y2 + b*y3 + c1*y4
     dem65 =~ y5 + a2*y6 + b*y7 + c2*y8

  # regressions
    dem60 ~ ind60
    dem65 ~ ind60 + dem60

  # residual correlations
    y1 ~~ y5
    y2 ~~ y4 + y6
    y3 ~~ y7
    y4 ~~ y8
    y6 ~~ y8
'

model_list <- mxsem(model = model,
                    data  = OpenMx::Bollen,
                    return_parameter_table = TRUE)

print(model_list$parameter_table)
```

