// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// clean_syntax
std::vector<std::string> clean_syntax(const std::string& syntax);
RcppExport SEXP _xsem_clean_syntax(SEXP syntaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type syntax(syntaxSEXP);
    rcpp_result_gen = Rcpp::wrap(clean_syntax(syntax));
    return rcpp_result_gen;
END_RCPP
}
// char_in_string
bool char_in_string(const char c, const std::string& str);
RcppExport SEXP _xsem_char_in_string(SEXP cSEXP, SEXP strSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char >::type c(cSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type str(strSEXP);
    rcpp_result_gen = Rcpp::wrap(char_in_string(c, str));
    return rcpp_result_gen;
END_RCPP
}
// parameter_table_to_Rcpp
Rcpp::DataFrame parameter_table_to_Rcpp(const std::vector<std::string>& equations);
RcppExport SEXP _xsem_parameter_table_to_Rcpp(SEXP equationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type equations(equationsSEXP);
    rcpp_result_gen = Rcpp::wrap(parameter_table_to_Rcpp(equations));
    return rcpp_result_gen;
END_RCPP
}
// split_string_all
std::vector<std::string> split_string_all(const std::string& str, const std::string& at);
RcppExport SEXP _xsem_split_string_all(SEXP strSEXP, SEXP atSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type str(strSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type at(atSEXP);
    rcpp_result_gen = Rcpp::wrap(split_string_all(str, at));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xsem_clean_syntax", (DL_FUNC) &_xsem_clean_syntax, 1},
    {"_xsem_char_in_string", (DL_FUNC) &_xsem_char_in_string, 2},
    {"_xsem_parameter_table_to_Rcpp", (DL_FUNC) &_xsem_parameter_table_to_Rcpp, 1},
    {"_xsem_split_string_all", (DL_FUNC) &_xsem_split_string_all, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_xsem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
