name: R CMD as-cran check Ubuntu

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-as-cran:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.r-version }})

    strategy:
      matrix:
        r-version: ['release']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: r-lib/actions/setup-r@v2
      - name: install compiled packages
        run: |
          sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
          sudo apt install --no-install-recommends r-cran-openmx
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - name: Check
        run: rcmdcheck::rcmdcheck(path = ".", args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
